version: '3'

services:

 go_db_service:

   image: postgres

   container_name: godbpostgress

   environment:

     - POSTGRES_USER=edteam

     - POSTGRES_PASSWORD=edteam

     - POSTGRES_DB=godb
     

   ports:

      - "5432:5432"

   volumes:

     - ./postgres-data:/var/lib/postgresql/data

 pg_admin:
  depends_on:
      - go_db_service
  image: dpage/pgadmin4
  volumes:
      - ./pgadmin:/var/lib/pgadmin
  container_name: pgadmin
  environment:
    - PGADMIN_DEFAULT_PASSWORD=123456
    - PGADMIN_DEFAULT_EMAIL=nahuel@google.com
  ports:
      - "8080:80"
